name: Test Suite
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-16.04

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12]

    steps:
      - name: Clone repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - run: node --version
      - run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
